import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar.jsx"; // 1. Import the Navbar

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {/* 2. Place the Navbar here */}
        {children}
      </body>
    </html>
  );
}